### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by jas14** [veloce/capacitor-stockfish#5]
```bash
make -C node_modules/capacitor-stockfish/stockfish/src/ build
...
main.cpp:49:8: error: no member named 'loop' in namespace 'Stockfish::UCI'
  UCI::loop(argc, argv);
  ~~~~~^
1 error generated.
make[1]: *** [main.o] Error 1
make: *** [build] Error 2
```

I'm not sure how this happened, but it appears `UCI::loop` was renamed `UCI::command`, but is still expected to be the latter:

https://github.com/veloce/capacitor-stockfish/blob/9bdcefe6c6d689219c1a6b00beccb38d4f4d104d/stockfish/src/uci.cpp#L225-L231

**Comment by jas14** [comment]
Ah, I see. This has been rewritten to take single commands from the caller instead of running a CLI loop.

**Comment by veloce** [comment]
You cannot directly build the project anymore from `stockfish/src` indeed, it has to be built from gradle and android ndk.
